# Generated by Django 6.0.1 on 2026-02-26 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='craft_process',
            field=models.TextField(blank=True, help_text='Step-by-step explanation of how this product is made'),
        ),
        migrations.AddField(
            model_name='product',
            name='cultural_story',
            field=models.TextField(blank=True, help_text='The story behind this craft and its cultural significance'),
        ),
        migrations.AddField(
            model_name='product',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='Social impact score (0-100) representing artisan empowerment'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this product has been verified by a cultural consultant'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, help_text='Geographic region or origin of the craft', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Cultural consultant who verified this product', limit_choices_to={'role': 'CONSULTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
