# Generated by Django 6.0.1 on 2026-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_craft_process_product_cultural_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verification_note',
            field=models.TextField(blank=True, help_text='Consultant note for verification or rejection'),
        ),
        migrations.AddField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Consultant verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When verification decision was made', null=True),
        ),
    ]
