# Generated by Django 6.0.1 on 2026-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_verification_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
